worker_processes  auto;
pid /tmp/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 8080;
        server_name  localhost;

        location / {
          proxy_pass  http://todo-ui:3000;
          proxy_set_header Host $host;
        }

        location /todos {
          proxy_pass  http://todo-api:8000;
          proxy_set_header Host $host;
        }

        # INFO: phpmyadmin produktiv nie ins internet exposen!
        # leitet http://localhost:8080/admin/index.php nach http://phpmyadmin/index.php
        location /admin/ {
          rewrite ^/admin(/.*)$ $1 break;
          proxy_pass  http://phpmyadmin;
          proxy_set_header Host $host;
        }
        

    }
}
